import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Operation = {operationId:string; orderId:string; amountMinor:number; currency:string};
type Capture = Operation & {effectId:number; idempotencyKey:string|null};
type RecordedEvent = {type:string; operationId?:string; attempt?:number; effectId?:number; amountMinor?:number; currency?:string; boundary?:{checkpoint:string}};
type Case = {worldId:string; label:string; verdict:string; elapsedSeconds:number; buildDigest:string; plan:{variant:string; operations:Operation[]; actions:unknown[]}; observation:{ledger:Capture[]; application:Record<string,unknown>[]} | null; events:RecordedEvent[]; diagnostics:string[]; properties:{property:string;passed:boolean;operationId:string;detail:string}[]; replayMatched?:boolean; comparison?:boolean};
type Reduction = {beforeActions:number; afterActions:number; oneMinimal:boolean; case:Case};
type Campaign = {id:string; variant:string; lifecycle:string; operation:Operation; cases:Case[]; counts:Record<string,number>; discoveredCheckpoints:string[]; executed:number; reduction?:Reduction};
type Job = {id:string; kind:string; lifecycle:string; error?:string; result:unknown};
type Fixtures = {variants:Record<string,string>; readOnly:boolean; tokenRequired:boolean; activeJob:string|null};
const PASS='PASS_WITHIN_BOUNDS', FAIL='PROPERTY_VIOLATION';
const pretty=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const tone=(v?:string)=>v===PASS?'pass':v===FAIL?'fail':v?'warn':'neutral';
const money=(minor:number,currency='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:minor%100?2:0}).format(minor/100);
function Badge({value}:{value?:string}) { return <span className={'badge '+tone(value)}><i/>{value===PASS?'Pass within bounds':value===FAIL?'Property violation':value?pretty(value):'Not run'}</span> }
function Icon({name}:{name:'logo'|'play'|'grid'|'file'|'arrow'}) { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{name==='logo'?<><path d="M12 2 21 7v10l-9 5-9-5V7z"/><path d="m7 12 3 3 7-7"/></>:name==='play'?<path d="m9 5 10 7-10 7z"/>:name==='grid'?<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>:name==='file'?<><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 12h6M9 16h6"/></>:<path d="M5 12h14m-5-5 5 5-5 5"/>}</svg> }

function App(){
 const [fixtures,setFixtures]=useState<Fixtures|null>(null),[error,setError]=useState('');
 const [variant,setVariant]=useState('local_dedup'),[amount,setAmount]=useState(100000),[operationId,setOperationId]=useState('capture-001');
 const [campaign,setCampaign]=useState<Campaign|null>(null),[selected,setSelected]=useState<string|null>(null);
 const [job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[recorded,setRecorded]=useState(false);
 const [comparison,setComparison]=useState<Case|null>(null),[replayed,setReplayed]=useState<Case|null>(null);
 const [history,setHistory]=useState<{id:string;variant:string;lifecycle:string}[]>([]);
 const [token,setToken]=useState(()=>sessionStorage.getItem('stateproof-token')||'');
 async function api<T>(url:string,body?:unknown):Promise<T>{
  const r=await fetch('/api'+url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  if(!r.ok){let detail;try{detail=(await r.json()).detail}catch{detail=`HTTP ${r.status}`}throw new Error(typeof detail==='string'?detail:JSON.stringify(detail))}
  return r.json();
 }
 async function connect(){try{const f=await api<Fixtures>('/fixtures');setFixtures(f);setHistory(await api('/campaigns'));if(f.activeJob)setJob(await api<Job>('/jobs/'+f.activeJob));setError('')}catch(e){setFixtures(null);setError('Cannot connect to the runner. '+String(e))}}
 useEffect(()=>{void connect()},[]);
 useEffect(()=>{if(!job||job.lifecycle!=='RUNNING')return;let stopped=false;
  const tick=async()=>{try{const j=await api<Job>('/jobs/'+job.id);if(stopped)return;setJob(j);
   if(j.kind==='campaign'){try{setCampaign(await api<Campaign>('/campaigns/'+j.id))}catch(e){if(j.lifecycle!=='RUNNING')throw e}}
   if(j.lifecycle!=='RUNNING'){
    if(j.error)setError(j.error);
    if(j.kind==='reduce'&&campaign)setCampaign(await api<Campaign>('/campaigns/'+campaign.id));
    if(j.kind==='comparison')setComparison(j.result as Case);
    if(j.kind==='replay')setReplayed(j.result as Case);
    setHistory(await api('/campaigns'));
   }
  }catch(e){if(!stopped)setError(String(e))}};
  const timer=setInterval(()=>void tick(),700);void tick();return()=>{stopped=true;clearInterval(timer)};
 },[job?.id,job?.lifecycle]);
 const running=busy||job?.lifecycle==='RUNNING', disabled=running||!fixtures||fixtures.readOnly;
 const current=campaign?.cases.find(c=>c.worldId===selected)||campaign?.cases.find(c=>c.verdict===FAIL)||campaign?.cases.at(-1);
 const operation=campaign?.operation;
 const captures=current?.observation?.ledger.filter(r=>r.operationId===operation?.operationId)||[];
 const total=captures.reduce((n,r)=>n+r.amountMinor,0);
 const failure=campaign?.cases.some(c=>c.verdict===FAIL);
 const originalFailure=campaign?.reduction?.case||campaign?.cases.find(c=>c.verdict===FAIL);
 async function act(path:string,body:unknown={}){setBusy(true);setError('');try{setJob(await api<Job>(path,body))}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function run(){setCampaign(null);setSelected(null);setComparison(null);setReplayed(null);setRecorded(false);await act('/campaigns',{variant,operation:{operationId,orderId:'order-001',amountMinor:amount,currency:'INR'}})}
 async function restore(id:string){if(!id)return;try{setCampaign(await api('/campaigns/'+id));setRecorded(true);setSelected(null);setComparison(null);setReplayed(null);setJob(null)}catch(e){setError(String(e))}}
 async function download(){if(!campaign)return;setBusy(true);try{const r=await fetch(`/api/campaigns/${campaign.id}/evidence`);if(!r.ok)throw new Error(await r.text());const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`stateproof-${campaign.id}.zip`;a.click();URL.revokeObjectURL(url)}catch(e){setError(String(e))}finally{setBusy(false)}}
 const timedEvents=current?.events.filter(e=>['delivery','effect_committed','worker_terminated','ack'].includes(e.type))||[];
 return <div className="shell">
  <aside className="sidebar"><a href="/" className="brand"><span className="brandmark"><Icon name="logo"/></span>StateProof<span className="version">/ 01</span></a><div className="workspace-label">ENGINEERING WORKSPACE</div><a className="nav active" href="#lab"><Icon name="grid"/>Retry lab<span>01</span></a><a className="nav" href="#evidence"><Icon name="file"/>Evidence explorer</a><div className="rail-note"><div className="rail-symbol">↻</div><strong>Trust the effect.<br/>Test the retry.</strong><p>Real worker failures.<br/>Independent durable evidence.</p></div><div className="rail-bottom"><span className="tiny-dot"/>Local / CI runner<div>Seeded payment benchmark</div></div></aside>
  <div className="body"><header><div>Workspace <span className="slash">/</span> <strong>Payment capture</strong></div><div className="connection"><i className={fixtures?'online':''}/>{fixtures?'Runner connected':'Connecting to runner'}<span className="header-tag">BOUNDED EXPLORATION</span></div></header>
   <main id="lab"><div className="title-row"><div><div className="eyebrow">RETRY CORRECTNESS LAB</div><h1>One payment. Every retry counts.</h1><p className="subtitle">Interrupt a real consumer. Redeliver the operation. Inspect what actually happened.</p></div><span className="sample-chip">SAMPLE FIXTURE <b>payment-v1</b></span></div>
   {error&&<div role="alert" className="error"><strong>Action needs attention</strong><span>{error}</span><button onClick={()=>void connect()}>Reconnect</button></div>}
   {fixtures?.readOnly&&<div className="notice">Read-only deployment · Explore saved evidence below. Execution is available to the operator through the CLI.</div>}
   {fixtures?.tokenRequired&&<label className="token">Operator token <input type="password" value={token} onChange={e=>{setToken(e.target.value);sessionStorage.setItem('stateproof-token',e.target.value)}} placeholder="Required to run tests"/></label>}
   <section className="config panel"><div className="section-heading"><span className="step">01</span><h2>Configure the experiment</h2><span className="muted">Trusted fixture · real execution</span></div><div className="config-grid"><label>Fixture<select disabled><option>Payment capture / INR</option></select></label><label>Implementation<select value={variant} disabled={running} onChange={e=>setVariant(e.target.value)}>{Object.keys(fixtures?.variants||{local_dedup:''}).map(v=><option key={v} value={v}>{v}{v==='stable_key'?' · repaired benchmark':''}</option>)}</select></label><label>Payment amount <span>(paise)</span><input type="number" min="1" max="100000000" value={amount} disabled={running} onChange={e=>setAmount(Number(e.target.value))}/></label><button className="primary run" disabled={disabled} onClick={()=>void run()}><Icon name="play"/>{running?'Execution in progress':'Run exploration'}</button></div><div className="config-footer"><span className="code-note">{fixtures?.variants[variant]||'Loading implementation details…'}</span><div className="bounds"><span>1 worker</span><span>1 crash / case</span><span>1 retry</span><span>15s / attempt</span></div></div><details className="operation-options"><summary>Operation identity</summary><label>Logical operation ID<input value={operationId} pattern="[a-zA-Z0-9_-]{1,64}" onChange={e=>setOperationId(e.target.value)} disabled={running}/></label><p>Remains stable across attempts. Use a different ID for a separately intended capture.</p></details></section>
   <div className="section-heading results-heading"><span className="step">02</span><h2>Execution & evidence</h2><div className="history"><select aria-label="Saved campaigns" value={recorded?campaign?.id||'':''} disabled={running} onChange={e=>void restore(e.target.value)}><option value="">Open a saved campaign</option>{history.map(c=><option key={c.id} value={c.id}>{c.variant} · {c.id.slice(0,8)} · {c.lifecycle.toLowerCase()}</option>)}</select></div></div>
   <div className="control-grid">{['Normal delivery','Ordinary duplicate delivery'].map((label,i)=><div className="control-card" key={label}><span className="control-number">0{i+1}</span><div><strong>{label}</strong><p>{i===0?'One operation, one delivery':'Same operation delivered twice'}</p></div><Badge value={campaign?.cases[i]?.verdict}/></div>)}</div>
   {!campaign?<section className="empty panel"><div className="empty-icon"><Icon name="logo"/></div><h3>{running?'Starting an isolated world…':'A passing test is only the beginning.'}</h3><p>{running?'The runner is creating durable application and provider state.':'Run the controls, then explore each checkpoint observed in a normal execution.'}</p><div className="empty-flow"><span>Deliver</span><b>→</b><span>Interrupt</span><b>→</b><span>Retry</span><b>→</b><span>Verify</span></div></section>:<>
    <div className="campaign-status"><div><span className={'status-dot '+(running?'pulse':'')}/><strong>{recorded?'Saved campaign':campaign.lifecycle==='CANCELLED'?'Campaign cancelled':campaign.lifecycle==='INTERRUPTED'?'Campaign interrupted':running?'Running exploration':'Campaign recorded'}</strong><code>{campaign.id.slice(0,12)}</code></div><div><span>{campaign.executed||0} cases executed</span><span>{campaign.counts[FAIL]||0} violations</span><span>{campaign.counts.INCONCLUSIVE||0} inconclusive</span><span>{(campaign.counts.HARNESS_ERROR||0)+(campaign.counts.DIVERGED||0)} errors / diverged</span><span>{campaign.discoveredCheckpoints.length} observed sites</span>{running&&<button className="cancel" onClick={()=>void api('/jobs/'+job?.id+'/cancel',{}).catch(e=>setError(String(e)))}>Cancel run</button>}</div></div>
    <div className="experiment-grid"><section className="case-panel panel"><div className="panel-title"><h3>Executed cases</h3><span>{campaign.cases.length}</span></div><div className="case-list">{campaign.cases.map((c,i)=><button key={c.worldId} className={'case '+(current?.worldId===c.worldId?'selected':'')} onClick={()=>setSelected(c.worldId)}><span className={'case-dot '+tone(c.verdict)}/><div><strong>{c.label.replace('crash at ','')}</strong><small>{c.label.startsWith('crash')?'Worker kill + redelivery':c.label==='mixed workload'?'Includes unrelated work':'Control'} · {c.elapsedSeconds.toFixed(1)}s</small></div><span className="case-index">{String(i+1).padStart(2,'0')}</span></button>)}</div><div className="case-foot">Bounded coverage of observed sites.<br/>No claim about the full state space.</div></section>
    <section className="outcome panel" id="evidence"><div className="panel-title"><div><span className="eyebrow">BUSINESS OUTCOME</span><h3>{current?.label||'Waiting for the first result'}</h3></div><Badge value={current?.verdict}/></div><div className="money-grid"><div><span>Intended capture</span><strong>{money(operation?.amountMinor||0,operation?.currency)}</strong><small>One logical operation</small></div><div className={tone(current?.verdict)}><span>Provider captured</span><strong>{current?.observation?money(total,operation?.currency):'—'}</strong><small>{current?.observation?`${captures.length} committed effect${captures.length===1?'':'s'}`:'Evidence unavailable'}</small></div></div>
     {current?.verdict===FAIL&&<div className="violation-note"><span>!</span><div><strong>{captures.length>1?'A retry repeated the external effect.':'Local completion does not match the provider.'}</strong><p>{captures.length>1?'The provider ledger contains more than one capture for this operation.':'A paid operation must have exactly one matching capture.'}</p></div></div>}
     {!!current?.diagnostics.length&&<div className="notice">{current.diagnostics.join(' · ')}</div>}
     <div className="timeline-header"><h4>Recorded execution</h4><span>Ordered events · {current?.worldId.slice(0,8)}</span></div><ol className="timeline">{timedEvents.map((e,i)=><li key={i} className={e.type==='worker_terminated'?'crash':e.type==='effect_committed'?'effect':''}><span className="event-mark"/><span className="event-number">{String(i+1).padStart(2,'0')}</span><div><strong>{e.type==='delivery'?e.attempt===2?'Retry delivered':'Operation delivered':e.type==='effect_committed'?'Provider effect committed':e.type==='worker_terminated'?'Worker terminated':'Delivery acknowledged'}</strong><small>{e.type==='worker_terminated'?e.boundary?.checkpoint:e.operationId}</small></div><span className="event-value">{e.type==='effect_committed'?money(e.amountMinor||0,e.currency):e.type==='delivery'?`attempt ${e.attempt}`:e.type==='worker_terminated'?'process killed':'ack'}</span></li>)}</ol>
    </section></div>
    <div className="state-grid"><section className="panel"><div className="panel-title"><h3>Independent provider ledger</h3><span className="storage-label">SQLite · durable</span></div><div className="table-scroll"><table><thead><tr><th>Effect</th><th>Operation</th><th>Amount</th><th>Provider key</th></tr></thead><tbody>{current?.observation?.ledger.map(r=><tr key={r.effectId}><td>#{r.effectId}</td><td><code>{r.operationId}</code></td><td>{money(r.amountMinor,r.currency)}</td><td className="key-cell" title={r.idempotencyKey||'No key'}>{r.idempotencyKey||<span className="muted">No key</span>}</td></tr>)}</tbody></table>{!current?.observation?.ledger.length&&<p className="table-empty">{current?.observation?'No committed captures.':'No provider evidence available.'}</p>}</div></section><section className="panel"><div className="panel-title"><h3>Application state</h3><span className="storage-label">PostgreSQL</span></div>{current?.observation?.application.length?<div className="app-rows">{current.observation.application.map((r,i)=><div key={i}><code>{String(r.operation_id)}</code><span className="local-status">{String(r.status)}</span><small>recorded effect: {String(r.effect_id??'none')}</small></div>)}</div>:<p className="table-empty">{current?.observation?'No local completion recorded.':'Application evidence unavailable.'}</p>}<p className="state-foot">Local status alone cannot establish payment correctness.</p></section></div>
    <section className="panel regression"><div className="section-heading"><span className="step">03</span><h2>Turn the failure into a regression case</h2></div><div className="action-row"><div><h3>{campaign.reduction?`${campaign.reduction.beforeActions} → ${campaign.reduction.afterActions} actions`:'Keep only what reproduces the failure.'}</h3><p>{campaign.reduction?(campaign.reduction.oneMinimal?'Verified 1-minimal under prerequisite-preserving action deletion.':'Reduction incomplete; minimality not established.'):'Delete actions, rerun in fresh worlds, retain the same property and operation.'}</p></div><div className="actions"><button disabled={disabled||!failure} onClick={()=>void act(`/campaigns/${campaign.id}/reduce`)}>Reduce workload</button><button disabled={disabled||!current} onClick={()=>void act('/replays',{campaignId:campaign.id})}>Replay case</button><button className="dark" disabled={disabled||!failure} onClick={()=>void act('/replays',{campaignId:campaign.id,comparisonVariant:'stable_key'})}>Compare stable key <Icon name="arrow"/></button></div></div>
     {job&&job.kind!=='campaign'&&<div className="job-status" role="status">{pretty(job.kind)} · {pretty(job.lifecycle)}{job.lifecycle==='RUNNING'&&<button onClick={()=>void api('/jobs/'+job.id+'/cancel',{}).catch(e=>setError(String(e)))}>Cancel job</button>}</div>}
     {replayed&&<div className="replay-result"><Badge value={replayed.verdict}/><span>{replayed.replayMatched?'Replay matched the saved evidence contract.':'Replay did not establish a match. Inspect diagnostics.'}</span><span>{replayed.diagnostics?.join(' · ')}</span></div>}
     {comparison&&<div className="comparison"><div><span className="eyebrow">ORIGINAL BENCHMARK</span><h3>{campaign.variant}</h3><Badge value={originalFailure?.verdict}/><strong className="text-fail">{money(originalFailure?.observation?.ledger.filter(r=>r.operationId===operation?.operationId).reduce((s,r)=>s+r.amountMinor,0)||0,operation?.currency)} captured</strong><code>{campaign.variant==='mark_before'?'persist paid → call provider':'provider key absent or changes across attempts'}</code></div><div><span className="eyebrow">SAME FAULT PLAN · REPAIR COMPARISON</span><h3>stable_key</h3><Badge value={comparison.verdict}/><strong>{comparison.observation?money(comparison.observation.ledger.filter(r=>r.operationId===operation?.operationId).reduce((s,r)=>s+r.amountMinor,0)||0,operation?.currency)+' captured':'Evidence unavailable'}</strong><code>key = "stateproof:payment:v1:" + operationId</code><p>Provider deduplicates the logical capture; local success is written afterward. Selected benchmark repair, not automatic code repair.</p></div></div>}
     <details className="technical"><summary>Property checks & replay details</summary><div>{current?.properties.map((p,i)=><p key={i}><span className={p.passed?'text-pass':'text-fail'}>{p.passed?'PASS':'FAIL'}</span> <code>{p.property}</code> · {p.operationId} — {p.detail}</p>)}</div><code>Build SHA-256: {current?.buildDigest}</code><p>Replay normalizes process IDs, ports and world names; meaningful operation, amount, key and fault relationships remain. This is not full-machine determinism.</p></details>
     <div className="export-row"><div><Icon name="file"/><span>Manifest, observations, SQLite ledgers & SHA-256 checksums</span></div><button disabled={running||campaign.lifecycle==='RUNNING'} onClick={()=>void download()}>Download evidence ↓</button></div></section>
   </>}
   <footer><span><Icon name="logo"/>StateProof <b>·</b> Evidence over assumptions.</span><span>Seeded benchmark. Bounded results. No production-bug discovery claim.</span></footer>
  </main></div></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
